--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Catalyst-Serendipity/PlayerAnalyticsHub
build-by-default: true
branches:
- main
projects:
  PlayerAnalyticsHub:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^4.2.0
        branch: pm5

...
